// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Promocode struct {
	ID               uuid.UUID `json:"id"`
	Code             string    `json:"code"`
	DiscountType     string    `json:"discount_type"`
	DiscountValue    int32     `json:"discount_value"`
	MaxActivations   int32     `json:"max_activations"`
	ActivationsCount int32     `json:"activations_count"`
	ExpiresAt        time.Time `json:"expires_at"`
	CreatedAt        time.Time `json:"created_at"`
}

type PromocodeRedemption struct {
	ID          uuid.UUID `json:"id"`
	PromocodeID uuid.UUID `json:"promocode_id"`
	UserID      string    `json:"user_id"`
	RedeemedAt  time.Time `json:"redeemed_at"`
}
